site_name: AList3SDK
repo_url: https://github.com/moyanj/AList3SDK/

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
          setup_commands:
            - import sys
            - sys.path.insert(0, "..")

nav:
  - 主页: "index.md"
  - 开始: "guide.md"
  - API参考: 
    - "apis/main.md"
    - "apis/model.md"
    - "apis/sync.md"
    - "apis/utils.md"
    - "apis/error.md"
  - 示例:
    - "examples/first.md"
    
theme:
  name: material
  language: 'zh'  # 配置语言
  
markdown_extensions:
  - admonition  # 提示块
  - footnotes  # 脚注
  - meta  # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret  # 下划线上标
  - pymdownx.tilde  # 删除线下标
  - pymdownx.critic  # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details  # 提示块可折叠
  - pymdownx.inlinehilite  # 行内代码高亮
  - pymdownx.mark  # 文本高亮
  - pymdownx.smartsymbols  # 符号转换
  - pymdownx.superfences  # 代码嵌套在列表里
  - codehilite:    # 代码高亮，显示行号
      guess_lang: false
      linenums: true
  - toc:  # 锚点
      permalink: true
  - pymdownx.arithmatex  # 数学公式
  - pymdownx.betterem:  # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.emoji:  # 表情
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink  # 自动识别超链接
  - pymdownx.tasklist:  # 复选框checklist
      custom_checkbox: true