# action的名称
name: Test

on: 
  - push
  - pull_request


jobs:
  deploy:
    name: publish python package to PYPI
    # 此作业在 Linux 上运行
    runs-on: ubuntu-latest

    steps:
    # 此步骤使用 GitHub 的 https://github.com/actions/checkout
    - uses: actions/checkout@v4

    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt

    #测试
    - name: Test
      run: |
        python -m pytest